version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: shridharpoman
      POSTGRES_PASSWORD: pune12345
      POSTGRES_DB: postgres