spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: shridharpoman
    password: pune12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# Other Spring configuration properties

